[package]
name = "comptime_cranelift"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]

cranelift = "0.111.0"
cranelift-module = "0.111.0"
cranelift-jit = "0.111.0"
cranelift-native = "0.111.0"

[workspace]
