id = "franca"
name = "Franca"
description = "..."
version = "0.0.1"
schema_version = 1
authors = ["L"]
repository = "https://github.com/LukeGrahamLandry/franca"

[language_servers.franca]
name = "Franca"
language = "Franca"
