[package]
name = "franca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-franca = { path = "./grammar" }
tree-sitter = "~0.20.10"
interp_derive = { path = "interp_derive" }

[features]
spam_log = ["some_log"]
some_log = []

[profile.release]
strip = "debuginfo"
panic = "abort"
# lto = true
