[package]
name = "franca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interp_derive = { path = "interp_derive" }
codemap = "0.1.3"
codemap-diagnostic = { git = "https://github.com/Johan-Mi/codemap-diagnostic", version = "0.1.1" }
libffi = { version = "3.2.0", optional = true }
libc = { version = "0.2.153", optional = true }

[features]
default = ["some_log", "interp_c_ffi"]
spam_log = ["some_log"]
some_log = []
interp_c_ffi = ["dep:libffi", "dep:libc"]

[profile.release]
strip = "debuginfo"
# panic = "abort"
# lto = true
