[package]
name = "franca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interp_derive = { path = "interp_derive" }
codemap = "0.1.3"
codemap-diagnostic = { git = "https://github.com/Johan-Mi/codemap-diagnostic", version = "0.1.1" }

[features]
default = ["some_log"]
spam_log = ["some_log"]
some_log = []

[profile.release]
strip = "debuginfo"
panic = "abort"
# lto = true
