[package]
name = "franca"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]

[dependencies]
libc = { version = "0.2.153" }
backtrace = { version = "0.3", features = ["std"], optional = true }
rustc-hash = "1.1"
memmap2 = "0.9.4"
cranelift = { version = "0.107.2", optional = true }
cranelift-module = { version = "0.107.2", optional = true }
cranelift-jit = { version = "0.107.2", optional = true }
cranelift-native = { version = "0.107.2", optional = true }
cranelift-object = { version = "0.107.2", optional = true }

[profile.dev.package."*"]
opt-level = 3


[features]
default = ["backtracers", "cranelift", "c-backend"]
backtracers = ["dep:backtrace"]
cranelift = ["dep:cranelift", "dep:cranelift-module", "dep:cranelift-jit", "dep:cranelift-native", "dep:cranelift-object"]
be_thread_safe = []
c-backend = []
self_scope = []

[profile.release]
strip = "debuginfo"
panic = "abort"
# lto = true
# opt-level = "s"

[workspace]
members = [
    # TODO
    # "editors/lsp",
]
