[package]
name = "franca"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde_json = { version = "1.0.108" }
serde = { version = "1.0.192", features = ["derive"] }
libc = { version = "0.2.153" }
codemap = "0.1.3"
codemap-diagnostic = { git = "https://github.com/Johan-Mi/codemap-diagnostic", rev = "c7860a6dd8761bf35f5418b92dcdd0cadcd10d4e" }
libffi = { version = "3.2.0" }

[dependencies]
mir-sys = { path = "./crates/mir-sys", optional = true }
lsp = { path = "./crates/lsp", optional = true }
llvm-backend = { path = "./crates/llvm-backend", optional = true }
serde_json = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
codemap = { workspace = true }
codemap-diagnostic = { workspace = true }
compiler = { path = "./crates/compiler" }

[features]
default = ["some_log", "dis_debug", "llvm", "lsp", "mir", "clang_ast"]
spam_log = ["some_log"]
some_log = []
println_now = []
dis_debug = []
llvm = ["dep:llvm-backend"]
lsp = ["dep:lsp", "dep:serde", "dep:serde_json"]
mir = ["dep:mir-sys"]
clang_ast = ["dep:serde", "dep:serde_json"]

[profile.release]
# strip = "debuginfo"
# panic = "abort"
# lto = true

[workspace]
members = [
    "crates/mir-sys",
    "crates/lsp",
    "crates/llvm-backend",
    "crates/compiler",
    "crates/interp_derive",
]
