[package]
name = "franca"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interp_derive = { path = "interp_derive" }
codemap = "0.1.3"
codemap-diagnostic = { git = "https://github.com/Johan-Mi/codemap-diagnostic", rev = "c7860a6dd8761bf35f5418b92dcdd0cadcd10d4e" }
libffi = { version = "3.2.0", optional = true }
libc = { version = "0.2.153", optional = true }
llvm-sys = { version = "160.1.0", optional = true }
lsp-server = { version = "0.7.6", optional = true }
lsp-types = { version = "0.95", optional = true }
serde_json = { version = "1.0.108", optional = true }
serde = { version = "1.0.192", features = ["derive"], optional = true }

[target.'cfg(target_arch = "aarch64")'.dependencies]
memmap2 = "0.9.4"

[features]
default = ["some_log", "interp_c_ffi", "dis_debug", "llvm", "lsp"]
spam_log = ["some_log"]
some_log = []
interp_c_ffi = ["dep:libffi", "dep:libc"]
println_now = []
dis_debug = []
llvm = ["dep:llvm-sys"]
lsp = ["dep:lsp-server", "dep:lsp-types", "dep:serde_json", "dep:serde"]

[profile.release]
strip = "debuginfo"
# panic = "abort"
# lto = true
