[package]
name = "franca"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
codemap = "0.1.3"
codemap-diagnostic = { git = "https://github.com/Johan-Mi/codemap-diagnostic", rev = "c7860a6dd8761bf35f5418b92dcdd0cadcd10d4e" }

[dependencies]
codemap = { workspace = true }
codemap-diagnostic = { workspace = true }
libc = { version = "0.2.153" }
interp_derive = { path = "interp_derive" }
backtrace = { version = "0.3", features = ["std"] }
rustc-hash = "1.1"
libffi = { version = "3.2.0" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
memmap2 = "0.9.4"

[features]
default = ["some_log", "dis_debug", "trace_errors"]
spam_log = ["some_log"]
some_log = []
dis_debug = []
trace_errors = []

[profile.release]
strip = "debuginfo"
panic = "abort"
# lto = true
#opt-level = "s"

[workspace]
members = [
    "editors/lsp",
    "interp_derive",
]
