[package]
name = "franca"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
libc = { version = "0.2.153" }
codemap = "0.1.3"
codemap-diagnostic = { git = "https://github.com/Johan-Mi/codemap-diagnostic", rev = "c7860a6dd8761bf35f5418b92dcdd0cadcd10d4e" }
libffi = { version = "3.2.0" }

[dependencies]
llvm-backend = { path = "./crates/llvm-backend", optional = true }
codemap = { workspace = true }
codemap-diagnostic = { workspace = true }
compiler = { path = "./crates/compiler" }
libc = { workspace = true }

[features]
default = ["some_log", "dis_debug", "trace_errors"]
spam_log = ["some_log"]
some_log = ["compiler/some_log"]
dis_debug = []
llvm = ["dep:llvm-backend"]
trace_errors = ["compiler/trace_errors"]

[profile.release]
strip = "debuginfo"
panic = "abort"
#lto = true
#opt-level = "s"

[workspace]
members = [
    "editors/lsp",
    "crates/llvm-backend",
    "crates/compiler",
    "crates/interp_derive",
]
