//! Alas, if I want to target a new thing,
//! it's more likely that it spawns from the
//! ether with a C compiler than a Rust compiler.

#include <dlfcn.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/mman.h>
#include <unistd.h>

int main() {
  // TODO: this should be a bitflag. presumably PROT_NONE is always 0.
  //       distinguish between flags whose value is shifting (i.e. 0/1/2 vs
  //       1/2/4)
  printf("// START @generated by libc_constants.c\n");
  printf("OpenFlag :: @enum(i64) (Read = %d, Write = %d, ReadWrite = %d, "
         "Create = %d, Truncate = %d);\n",
         O_RDONLY, O_WRONLY, O_RDWR, O_CREAT, O_TRUNC);
  printf("MapProt :: @enum(i64) (Exec = %d, Read = %d, Write = %d);\n",
         PROT_EXEC, PROT_READ, PROT_WRITE);
  printf("MapFlag :: @enum(i64) (Private = %d, Anonymous = %d);\n", MAP_PRIVATE,
         MAP_ANONYMOUS);
  printf("Whence :: @enum(i64) (Set = %d, Cur = %d, End = %d);\n", SEEK_SET,
         SEEK_CUR, SEEK_END);
  printf("DlFlag :: @enum(i64) (Lazy = %d, Now = %d);\n", RTLD_LAZY, RTLD_NOW);
  printf("// END @generated by libc_constants.c\n");
  return 0;
}
