// franca examples/web/build.fr && node target/web/test.js
// TODO: less :paste from examples/web/main.js
import { Worker } from "worker_threads";
import { readFileSync, writeFileSync } from "fs";
import { spawn } from "child_process";
function assert(cond, msg) { if (!cond) { console.trace(msg); process.exit(1); } } 
process.chdir("target/web");

// waste of time: node's threads api doesn't match the browser's threads api?
const prelude = `
// @generated by tests/test.js
import { Worker, isMainThread, parentPort } from "worker_threads";
import { readFileSync } from "fs";
const self = {
    postMessage: (msg) => parentPort.postMessage(msg),
};
parentPort.on("message", (msg) => self.onmessage({ data: msg }));
globalThis.cancelAnimationFrame = () => {};
class XMLHttpRequest {
    open(_0, url, _1) { this.url = url; };
    send() {
        // no cheating using the internet. any deps should be listed in tests/deps.fr so they get mirrored. 
        const sha256 = this.url.slice(this.url.length - 64);
        if (isNaN(Number("0x" + sha256)) || sha256.includes(".")) return;
        this.response = readFileSync("../franca/fetch/" + sha256 + ".out");
        this.status = 200;
    }
}
`;
const worker_path = "./node_worker.js";
const worker_src = readFileSync("./worker.js");
writeFileSync(worker_path, prelude + worker_src);
const franca_path = "target/franca.out";
const rootfs_hash = process.argv[2];
assert(rootfs_hash.length == 64, "expected argv[2] = rootfs_hash");

// TODO: test more and stop duplicating this list everywhere. 
const tests = [
    "examples/mandelbrot.fr",
    "examples/sudoku.fr",
    "examples/kaleidoscope.fr",
    "examples/bf/bf2ir.fr", 
    "examples/bf/code_string.fr", 
    "examples/bf/c_string.fr", 
    "tests/exe/c_ffi.fr",
    // TODO: FEAT_JIT is very :SLOW on whatever node i have (v23.9.0) much worse than chrome (so hopefully just that v8 got better since i last wrote a js program)
    "examples/prospero.fr",  
];

let err_innerText = "";
let out_innerText = "";
let thread_pool = [];
let running_threads = [];
let worker = null;
const wasm_module = await WebAssembly.compile(readFileSync("target/demo.wasm"));

const handle = (resolve) => (msg) => {
    msg = msg.data;
    switch (msg.tag) {
        case "show": { out_innerText += msg.text; break;  }
        case "log": break;
        case "err": { err_innerText += msg.text; break; }
        case "done": { resolve(); break; }
        case "ready": break;
        case "spawn": {
            const w = get_worker(); 
            w.onmessage = (msg) => {
                if (msg.data.tag == "recycle") {
                    running_threads.splice(running_threads.indexOf(w));
                    // don't call reset here. the point is to avoid replaying all the jit events if they're in the same program. 
                    thread_pool.push(w);
                    return;
                }
                handle(() => {})(msg);
            };
            running_threads.push(w);
            w.postMessage({ tag: "start", args: [], child: msg.child, memory: msg.memory });
            break;
        }
        default: assert(false, msg);
    }
};

function get_worker() {
    if (thread_pool.length == 0) {
        const w = new Worker(worker_path, { type: "module" });
        w.on("message", (msg) => w.onmessage({ data: msg }));
        w.onmessage = (e) => assert(false, e);  // patched by caller
        assert(wasm_module !== undefined, "get_worker before load_wasm");
        w.postMessage({ tag: "setmodule", module: wasm_module });
        thread_pool.push(w);
    };
    return thread_pool.pop();
}

const start_worker = (args, resolve) => {
    assert(worker === null, "had worker");
    worker = get_worker();
    worker.onmessage = handle(resolve);
    const memory = new WebAssembly.Memory({ initial: 300, maximum: 1 << (32 - 16), shared: true, });
    worker.postMessage({ tag: "start", args: ["demo.wasm", "-rootfs_hash", rootfs_hash, ...args], memory }, []);
};

async function run_tests() {
    let failed = 0;
    const start = performance.now();
    for (const name of tests) {
        // i'm forcing native and wasm to run sequentially (instead of Promise.all()) 
        // because i want to get more meaningful time comparison. 
        async function measure(run) {
            out_innerText = "";
            err_innerText = "";
            const start = performance.now();
            await run();
            return { time: Math.round(performance.now() - start), out: out_innerText, err: err_innerText };
        }
        const n = await measure(async () => {
            const native = spawn(franca_path, [name], { 
                cwd: "../..",  // undo the chdir
                env: { FRANCA_NO_CACHE: "1", },  // make the timings fair
            });
            native.stdout.on('data', (data) => out_innerText += data);
            native.stderr.on('data', (data) => err_innerText += data);
            let status = await (new Promise((resolve) => native.on('close', resolve)));
            if (status !== 0) err_innerText += `status=${status}`;
        });
        const w = await measure(async () => {
            await new Promise((resolve) => start_worker(["-file", name, "-lang", "franca"], resolve));
            if (running_threads.length !== 0) err_innerText += "correct programs join their threads";
        });
        reset_worker();
        const ok = w.err.length == 0 && w.err == n.err && w.out == n.out;
        console.log(`name=${name}; ok=${ok}; native=${n.time}ms; wasm=${w.time}ms; ratio=${(w.time/n.time).toFixed(1)}x; output_size=${w.out.length};`);
        if (!ok) failed += 1;
    }
    console.log(`Passed ${tests.length - failed}/${tests.length} tests in ${Math.round(performance.now() - start)}ms.`);
    assert(failed === 0, "tests failed");
}

function reset_worker() {
    thread_pool.push(worker);
    worker = null;
    // any children that were still running might be stuck
    for (const w of running_threads) { w.terminate(); }
    running_threads = [];
    for (const w of thread_pool) { w.postMessage({ tag: "reset" }); }
}

if (process.argv.includes("-file")) {
    // cwd doesn't matter because demo.wasm doesn't use the real file system
    await new Promise((resolve) => start_worker(process.argv.slice(2), resolve));
    process.stdout.write(out_innerText);
    process.stderr.write(err_innerText);
    if (err_innerText.length !== 0) process.exit(1);
} else {
    // running multiple in a row reusing the compiled demo.wasm module is much faster than execing node many times
    await run_tests();
}
process.exit(0);
