[package]
name = "lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7.6"
lsp-types = "0.95"
serde_json = { workspace = true }
serde = { workspace = true }
compiler = { path = "../compiler" }
codemap = { workspace = true }
