name = "Franca"
grammar = "rust"
path_suffixes = ["fr"]
line_comments = ["//"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = true },
]
tab_size = 4