[package]
name = "lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7.6"
lsp-types = "0.95"
serde_json = { version = "1.0.108" }
serde = { version = "1.0.192", features = ["derive"] }
franca = { path = "../.." }
codemap = { workspace = true }
