name: tests
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        system: [macos-14, macos-15-intel, ubuntu-latest, ubuntu-24.04-arm]
    name: run_tests ${{ matrix.system }}
    runs-on: ${{ matrix.system }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: target/franca/fetch
          key: cache-deps-${{ hashFiles('tests/deps.fr') }}
      - run: ./boot/strap.sh
      - uses: actions/upload-artifact@v4
        with:
          name: built_on_${{ matrix.system }}
          path: target/release
  repro:
    name: repro and deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: target/franca/fetch
          key: cache-deps-${{ hashFiles('tests/deps.fr') }}
      - uses: actions/download-artifact@v4
        with: 
          path: .
      - run: diff built_on_macos-14 built_on_macos-15-intel
      - run: diff built_on_macos-14 built_on_ubuntu-latest
      - run: diff built_on_macos-14 built_on_ubuntu-24.04-arm
      - run: ./boot/strap.sh -no-test
      - run: ./target/f.out examples/web/build.fr
      - uses: actions/upload-pages-artifact@v3
        with:
          path: target/web
      - name: wnebsnite
        id: deployment
        uses: actions/deploy-pages@v4
